VOTEMORELIKENOTVOTE=input("Hello jury's did you like doing jury duty if so enter your ID badge")
if VOTEMORELIKENOTVOTE == "1231231231233213456":
    VO=input("Did you like jury duty")
    print("You may now leave")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("Input was:" +VO)
